to.install <- character()
if (!require(dplyr))
    to.install <- c(to.install, "dplyr")
if (!require(readr))
    to.install <- c(to.install, "readr")
if (!require(tidyr))
    to.install <- c(to.install, "tidyr")
if (length(to.install) > 0)
    install.packages(to.install)
rm(to.install)
